<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNcWosxp\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNcWosxp/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerNcWosxp.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerNcWosxp\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerNcWosxp\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'NcWosxp',
    'container.build_id' => '9f20d7c4',
    'container.build_time' => 1529074738,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerNcWosxp');
