version: '2'
services:
    postgres:
        image: postgres:9.6-alpine
        ports:
            - '5432:5432'
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: apigca

    redis:
        image: redis:alpine
        ports:
          - '6379:6379'

    php:
        build: docker/php-fpm
        volumes:
            - ./:/www/APIGoogleConsoleAdmin:cached
        links:
            - postgres
            - redis

    nginx:
        build: docker/nginx
        ports:
            - '8000:80'
        links:
            - php
        volumes_from:
            - php
        volumes:
            - ./var/logs/nginx/:/var/log/nginx:cached