<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.5BmxbYJ' shared service.

return $this->privates['.service_locator.5BmxbYJ'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('jsonApiResponse' => function (): \App\Utils\JsonApiResponse {
    return ($this->privates['App\Utils\JsonApiResponse'] ?? $this->load('getJsonApiResponseService.php'));
}, 'usuarioBusiness' => function (): \App\Business\UserBusiness {
    return ($this->privates['App\Business\UserBusiness'] ?? $this->load('getUserBusinessService.php'));
}, 'usuarioManager' => function (): \App\Manager\UsuarioManager {
    return ($this->privates['App\Manager\UsuarioManager'] ?? $this->load('getUsuarioManagerService.php'));
}, 'usuarioService' => function (): \App\Service\Google\UsuarioService {
    return ($this->privates['App\Service\Google\UsuarioService'] ?? $this->load('getUsuarioServiceService.php'));
}));
