<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.HMbKQFw' shared service.

return $this->privates['.service_locator.HMbKQFw'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('calendarioManager' => function (): \App\Manager\CalendarioManager {
    return ($this->privates['App\Manager\CalendarioManager'] ?? $this->load('getCalendarioManagerService.php'));
}, 'calendarioService' => function (): \App\Service\Google\CalendarioService {
    return ($this->privates['App\Service\Google\CalendarioService'] ?? $this->load('getCalendarioServiceService.php'));
}, 'jsonApiResponse' => function (): \App\Utils\JsonApiResponse {
    return ($this->privates['App\Utils\JsonApiResponse'] ?? $this->load('getJsonApiResponseService.php'));
}));
