<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'argument_resolver.service' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/ServiceValueResolver.php';

return $this->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\ServiceLocator(array('App\\Controller\\Api\\CalendarioController::deleteAction' => function () {
    return ($this->privates['.service_locator.HMbKQFw'] ?? $this->load('get_ServiceLocator_HMbKQFwService.php'));
}, 'App\\Controller\\Api\\CalendarioController::getAction' => function () {
    return ($this->privates['.service_locator.HMbKQFw'] ?? $this->load('get_ServiceLocator_HMbKQFwService.php'));
}, 'App\\Controller\\Api\\CalendarioController::getAllEventoAction' => function () {
    return ($this->privates['.service_locator.GxgUpP2'] ?? $this->load('get_ServiceLocator_GxgUpP2Service.php'));
}, 'App\\Controller\\Api\\CalendarioController::getEventoAction' => function () {
    return ($this->privates['.service_locator.GxgUpP2'] ?? $this->load('get_ServiceLocator_GxgUpP2Service.php'));
}, 'App\\Controller\\Api\\CalendarioController::postAction' => function () {
    return ($this->privates['.service_locator.HMbKQFw'] ?? $this->load('get_ServiceLocator_HMbKQFwService.php'));
}, 'App\\Controller\\Api\\CalendarioController::postEventoAction' => function () {
    return ($this->privates['.service_locator.GxgUpP2'] ?? $this->load('get_ServiceLocator_GxgUpP2Service.php'));
}, 'App\\Controller\\Api\\CalendarioController::postUsuarioAction' => function () {
    return ($this->privates['.service_locator.HMbKQFw'] ?? $this->load('get_ServiceLocator_HMbKQFwService.php'));
}, 'App\\Controller\\Api\\CalendarioController::putAction' => function () {
    return ($this->privates['.service_locator.HMbKQFw'] ?? $this->load('get_ServiceLocator_HMbKQFwService.php'));
}, 'App\\Controller\\Api\\CalendarioController::putEventoAction' => function () {
    return ($this->privates['.service_locator.GxgUpP2'] ?? $this->load('get_ServiceLocator_GxgUpP2Service.php'));
}, 'App\\Controller\\Api\\CalendarioController::removeEventoAction' => function () {
    return ($this->privates['.service_locator.z6uwYYD'] ?? $this->load('get_ServiceLocator_Z6uwYYDService.php'));
}, 'App\\Controller\\Api\\CalendarioController::removeUsuarioAction' => function () {
    return ($this->privates['.service_locator.HMbKQFw'] ?? $this->load('get_ServiceLocator_HMbKQFwService.php'));
}, 'App\\Controller\\Api\\CalendarioController::setViewHandler' => function () {
    return ($this->privates['.service_locator.0igcDxJ'] ?? $this->load('get_ServiceLocator_0igcDxJService.php'));
}, 'App\\Controller\\Api\\CursoController::deleteAction' => function () {
    return ($this->privates['.service_locator.CT1CP3P'] ?? $this->load('get_ServiceLocator_CT1CP3PService.php'));
}, 'App\\Controller\\Api\\CursoController::deleteEstudanteAction' => function () {
    return ($this->privates['.service_locator.CT1CP3P'] ?? $this->load('get_ServiceLocator_CT1CP3PService.php'));
}, 'App\\Controller\\Api\\CursoController::deleteProfessorAction' => function () {
    return ($this->privates['.service_locator.CT1CP3P'] ?? $this->load('get_ServiceLocator_CT1CP3PService.php'));
}, 'App\\Controller\\Api\\CursoController::getEstudanteAction' => function () {
    return ($this->privates['.service_locator.LM4.eV9'] ?? $this->load('get_ServiceLocator_LM4_EV9Service.php'));
}, 'App\\Controller\\Api\\CursoController::getProfessorAction' => function () {
    return ($this->privates['.service_locator.LM4.eV9'] ?? $this->load('get_ServiceLocator_LM4_EV9Service.php'));
}, 'App\\Controller\\Api\\CursoController::idAction' => function () {
    return ($this->privates['.service_locator.xOtYFb0'] ?? $this->load('get_ServiceLocator_XOtYFb0Service.php'));
}, 'App\\Controller\\Api\\CursoController::idEstudanteAction' => function () {
    return ($this->privates['.service_locator.CT1CP3P'] ?? $this->load('get_ServiceLocator_CT1CP3PService.php'));
}, 'App\\Controller\\Api\\CursoController::idProfessorAction' => function () {
    return ($this->privates['.service_locator.CT1CP3P'] ?? $this->load('get_ServiceLocator_CT1CP3PService.php'));
}, 'App\\Controller\\Api\\CursoController::postAction' => function () {
    return ($this->privates['.service_locator.326xauu'] ?? $this->load('get_ServiceLocator_326xauuService.php'));
}, 'App\\Controller\\Api\\CursoController::postEstudanteAction' => function () {
    return ($this->privates['.service_locator.LM4.eV9'] ?? $this->load('get_ServiceLocator_LM4_EV9Service.php'));
}, 'App\\Controller\\Api\\CursoController::postProfessorAction' => function () {
    return ($this->privates['.service_locator.LM4.eV9'] ?? $this->load('get_ServiceLocator_LM4_EV9Service.php'));
}, 'App\\Controller\\Api\\CursoController::putAction' => function () {
    return ($this->privates['.service_locator.326xauu'] ?? $this->load('get_ServiceLocator_326xauuService.php'));
}, 'App\\Controller\\Api\\CursoController::setViewHandler' => function () {
    return ($this->privates['.service_locator.0igcDxJ'] ?? $this->load('get_ServiceLocator_0igcDxJService.php'));
}, 'App\\Controller\\Api\\GrupoController::setViewHandler' => function () {
    return ($this->privates['.service_locator.0igcDxJ'] ?? $this->load('get_ServiceLocator_0igcDxJService.php'));
}, 'App\\Controller\\Api\\UsuarioController::deleteAction' => function () {
    return ($this->privates['.service_locator.Q4enjf6'] ?? $this->load('get_ServiceLocator_Q4enjf6Service.php'));
}, 'App\\Controller\\Api\\UsuarioController::idAction' => function () {
    return ($this->privates['.service_locator.Q4enjf6'] ?? $this->load('get_ServiceLocator_Q4enjf6Service.php'));
}, 'App\\Controller\\Api\\UsuarioController::postAction' => function () {
    return ($this->privates['.service_locator.5BmxbYJ'] ?? $this->load('get_ServiceLocator_5BmxbYJService.php'));
}, 'App\\Controller\\Api\\UsuarioController::setViewHandler' => function () {
    return ($this->privates['.service_locator.0igcDxJ'] ?? $this->load('get_ServiceLocator_0igcDxJService.php'));
}, 'App\\Controller\\Api\\UsuarioController::updateAction' => function () {
    return ($this->privates['.service_locator.Q4enjf6'] ?? $this->load('get_ServiceLocator_Q4enjf6Service.php'));
}, 'App\\Controller\\Api\\CalendarioController:deleteAction' => function () {
    return ($this->privates['.service_locator.HMbKQFw'] ?? $this->load('get_ServiceLocator_HMbKQFwService.php'));
}, 'App\\Controller\\Api\\CalendarioController:getAction' => function () {
    return ($this->privates['.service_locator.HMbKQFw'] ?? $this->load('get_ServiceLocator_HMbKQFwService.php'));
}, 'App\\Controller\\Api\\CalendarioController:getAllEventoAction' => function () {
    return ($this->privates['.service_locator.GxgUpP2'] ?? $this->load('get_ServiceLocator_GxgUpP2Service.php'));
}, 'App\\Controller\\Api\\CalendarioController:getEventoAction' => function () {
    return ($this->privates['.service_locator.GxgUpP2'] ?? $this->load('get_ServiceLocator_GxgUpP2Service.php'));
}, 'App\\Controller\\Api\\CalendarioController:postAction' => function () {
    return ($this->privates['.service_locator.HMbKQFw'] ?? $this->load('get_ServiceLocator_HMbKQFwService.php'));
}, 'App\\Controller\\Api\\CalendarioController:postEventoAction' => function () {
    return ($this->privates['.service_locator.GxgUpP2'] ?? $this->load('get_ServiceLocator_GxgUpP2Service.php'));
}, 'App\\Controller\\Api\\CalendarioController:postUsuarioAction' => function () {
    return ($this->privates['.service_locator.HMbKQFw'] ?? $this->load('get_ServiceLocator_HMbKQFwService.php'));
}, 'App\\Controller\\Api\\CalendarioController:putAction' => function () {
    return ($this->privates['.service_locator.HMbKQFw'] ?? $this->load('get_ServiceLocator_HMbKQFwService.php'));
}, 'App\\Controller\\Api\\CalendarioController:putEventoAction' => function () {
    return ($this->privates['.service_locator.GxgUpP2'] ?? $this->load('get_ServiceLocator_GxgUpP2Service.php'));
}, 'App\\Controller\\Api\\CalendarioController:removeEventoAction' => function () {
    return ($this->privates['.service_locator.z6uwYYD'] ?? $this->load('get_ServiceLocator_Z6uwYYDService.php'));
}, 'App\\Controller\\Api\\CalendarioController:removeUsuarioAction' => function () {
    return ($this->privates['.service_locator.HMbKQFw'] ?? $this->load('get_ServiceLocator_HMbKQFwService.php'));
}, 'App\\Controller\\Api\\CalendarioController:setViewHandler' => function () {
    return ($this->privates['.service_locator.0igcDxJ'] ?? $this->load('get_ServiceLocator_0igcDxJService.php'));
}, 'App\\Controller\\Api\\CursoController:deleteAction' => function () {
    return ($this->privates['.service_locator.CT1CP3P'] ?? $this->load('get_ServiceLocator_CT1CP3PService.php'));
}, 'App\\Controller\\Api\\CursoController:deleteEstudanteAction' => function () {
    return ($this->privates['.service_locator.CT1CP3P'] ?? $this->load('get_ServiceLocator_CT1CP3PService.php'));
}, 'App\\Controller\\Api\\CursoController:deleteProfessorAction' => function () {
    return ($this->privates['.service_locator.CT1CP3P'] ?? $this->load('get_ServiceLocator_CT1CP3PService.php'));
}, 'App\\Controller\\Api\\CursoController:getEstudanteAction' => function () {
    return ($this->privates['.service_locator.LM4.eV9'] ?? $this->load('get_ServiceLocator_LM4_EV9Service.php'));
}, 'App\\Controller\\Api\\CursoController:getProfessorAction' => function () {
    return ($this->privates['.service_locator.LM4.eV9'] ?? $this->load('get_ServiceLocator_LM4_EV9Service.php'));
}, 'App\\Controller\\Api\\CursoController:idAction' => function () {
    return ($this->privates['.service_locator.xOtYFb0'] ?? $this->load('get_ServiceLocator_XOtYFb0Service.php'));
}, 'App\\Controller\\Api\\CursoController:idEstudanteAction' => function () {
    return ($this->privates['.service_locator.CT1CP3P'] ?? $this->load('get_ServiceLocator_CT1CP3PService.php'));
}, 'App\\Controller\\Api\\CursoController:idProfessorAction' => function () {
    return ($this->privates['.service_locator.CT1CP3P'] ?? $this->load('get_ServiceLocator_CT1CP3PService.php'));
}, 'App\\Controller\\Api\\CursoController:postAction' => function () {
    return ($this->privates['.service_locator.326xauu'] ?? $this->load('get_ServiceLocator_326xauuService.php'));
}, 'App\\Controller\\Api\\CursoController:postEstudanteAction' => function () {
    return ($this->privates['.service_locator.LM4.eV9'] ?? $this->load('get_ServiceLocator_LM4_EV9Service.php'));
}, 'App\\Controller\\Api\\CursoController:postProfessorAction' => function () {
    return ($this->privates['.service_locator.LM4.eV9'] ?? $this->load('get_ServiceLocator_LM4_EV9Service.php'));
}, 'App\\Controller\\Api\\CursoController:putAction' => function () {
    return ($this->privates['.service_locator.326xauu'] ?? $this->load('get_ServiceLocator_326xauuService.php'));
}, 'App\\Controller\\Api\\CursoController:setViewHandler' => function () {
    return ($this->privates['.service_locator.0igcDxJ'] ?? $this->load('get_ServiceLocator_0igcDxJService.php'));
}, 'App\\Controller\\Api\\GrupoController:setViewHandler' => function () {
    return ($this->privates['.service_locator.0igcDxJ'] ?? $this->load('get_ServiceLocator_0igcDxJService.php'));
}, 'App\\Controller\\Api\\UsuarioController:deleteAction' => function () {
    return ($this->privates['.service_locator.Q4enjf6'] ?? $this->load('get_ServiceLocator_Q4enjf6Service.php'));
}, 'App\\Controller\\Api\\UsuarioController:idAction' => function () {
    return ($this->privates['.service_locator.Q4enjf6'] ?? $this->load('get_ServiceLocator_Q4enjf6Service.php'));
}, 'App\\Controller\\Api\\UsuarioController:postAction' => function () {
    return ($this->privates['.service_locator.5BmxbYJ'] ?? $this->load('get_ServiceLocator_5BmxbYJService.php'));
}, 'App\\Controller\\Api\\UsuarioController:setViewHandler' => function () {
    return ($this->privates['.service_locator.0igcDxJ'] ?? $this->load('get_ServiceLocator_0igcDxJService.php'));
}, 'App\\Controller\\Api\\UsuarioController:updateAction' => function () {
    return ($this->privates['.service_locator.Q4enjf6'] ?? $this->load('get_ServiceLocator_Q4enjf6Service.php'));
})));
