<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Manager\CursoManager' shared autowired service.

include_once $this->targetDirs[3].'/src/Manager/CursoManager.php';

return $this->privates['App\Manager\CursoManager'] = new \App\Manager\CursoManager();
