<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Manager\CalendarioManager' shared autowired service.

include_once $this->targetDirs[3].'/src/Manager/AbstractGoogleManager.php';
include_once $this->targetDirs[3].'/src/Manager/CalendarioManager.php';

return $this->privates['App\Manager\CalendarioManager'] = new \App\Manager\CalendarioManager(($this->services['doctrine.orm.default_entity_manager'] ?? $this->load('getDoctrine_Orm_DefaultEntityManagerService.php')));
