<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Manager\EventoManager' shared autowired service.

include_once $this->targetDirs[3].'/src/Manager/AbstractGoogleManager.php';
include_once $this->targetDirs[3].'/src/Manager/EventoManager.php';

return $this->privates['App\Manager\EventoManager'] = new \App\Manager\EventoManager(($this->services['security.token_storage'] ?? $this->services['security.token_storage'] = new \Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorage()), ($this->services['doctrine.orm.default_entity_manager'] ?? $this->load('getDoctrine_Orm_DefaultEntityManagerService.php')));
