<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Google_Client' shared autowired service.

include_once $this->targetDirs[3].'/vendor/google/apiclient/src/Google/Client.php';

$this->privates['Google_Client'] = $instance = new \Google_Client();

$instance->setApplicationName('Directory API PHP');
$instance->setAuthConfig(($this->targetDirs[3].'/src/Credencial/credencial.json'));
$instance->setAccessType('offline');
$instance->setSubject('adminintegracoes@edu.senai.br');

return $instance;
