<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Utils\JsonApiResponse' shared autowired service.

include_once $this->targetDirs[3].'/src/Utils/GoogleMessagesError.php';
include_once $this->targetDirs[3].'/src/Utils/JsonApiResponse.php';

return $this->privates['App\Utils\JsonApiResponse'] = new \App\Utils\JsonApiResponse(new \App\Utils\GoogleMessagesError(($this->services['translator'] ?? $this->getTranslatorService())));
