<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'security.authentication.provider.simple_preauth.main' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/security/Core/User/UserProviderInterface.php';
include_once $this->targetDirs[3].'/src/Security/ApiKeyUserProvider.php';
include_once $this->targetDirs[3].'/vendor/symfony/security/Core/User/UserCheckerInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/security/Core/User/UserChecker.php';
include_once $this->targetDirs[3].'/vendor/symfony/security/Core/Authentication/Provider/AuthenticationProviderInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/security/Core/Authentication/Provider/SimpleAuthenticationProvider.php';
include_once $this->targetDirs[3].'/vendor/symfony/security/Core/Authentication/SimpleAuthenticatorInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/security/Http/Authentication/SimplePreAuthenticatorInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/security/Http/Authentication/AuthenticationFailureHandlerInterface.php';
include_once $this->targetDirs[3].'/src/Security/ApiKeyAuthenticator.php';

return $this->privates['security.authentication.provider.simple_preauth.main'] = new \Symfony\Component\Security\Core\Authentication\Provider\SimpleAuthenticationProvider(($this->privates['App\Security\ApiKeyAuthenticator'] ?? $this->privates['App\Security\ApiKeyAuthenticator'] = new \App\Security\ApiKeyAuthenticator()), new \App\Security\ApiKeyUserProvider(($this->services['doctrine.orm.default_entity_manager'] ?? $this->load('getDoctrine_Orm_DefaultEntityManagerService.php'))), 'main', new \Symfony\Component\Security\Core\User\UserChecker());
