<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'snc_redis.doctrine_redis' shared service.

include_once $this->targetDirs[3].'/vendor/snc/redis-bundle/Factory/EnvParametersFactory.php';
include_once $this->targetDirs[3].'/vendor/predis/predis/src/Profile/ProfileInterface.php';
include_once $this->targetDirs[3].'/vendor/predis/predis/src/Profile/RedisProfile.php';
include_once $this->targetDirs[3].'/vendor/predis/predis/src/Profile/RedisVersion320.php';
include_once $this->targetDirs[3].'/vendor/predis/predis/src/Configuration/OptionsInterface.php';
include_once $this->targetDirs[3].'/vendor/predis/predis/src/Configuration/Options.php';
include_once $this->targetDirs[3].'/vendor/predis/predis/src/ClientInterface.php';
include_once $this->targetDirs[3].'/vendor/predis/predis/src/Client.php';

return $this->services['snc_redis.doctrine_redis'] = new \Predis\Client(\Snc\RedisBundle\Factory\EnvParametersFactory::create(array('read_write_timeout' => NULL, 'iterable_multibulk' => false, 'serialization' => 'default', 'profile' => 'default', 'prefix' => NULL, 'service' => NULL, 'async_connect' => false, 'timeout' => 5, 'persistent' => false, 'exceptions' => true, 'logging' => false, 'alias' => 'doctrine_redis'), 'Predis\\Connection\\Parameters', $this->getEnv('REDIS_URL')), new \Predis\Configuration\Options(array('read_write_timeout' => NULL, 'iterable_multibulk' => false, 'serialization' => 'default', 'profile' => new \Predis\Profile\RedisVersion320(), 'prefix' => NULL, 'service' => NULL, 'async_connect' => false, 'timeout' => 5, 'persistent' => false, 'exceptions' => true)));
