<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'security.authentication.listener.simple_preauth.main' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/security/Http/Firewall/ListenerInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/security/Http/Firewall/SimplePreAuthenticationListener.php';
include_once $this->targetDirs[3].'/vendor/symfony/security/Core/Authentication/SimpleAuthenticatorInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/security/Http/Authentication/SimplePreAuthenticatorInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/security/Http/Authentication/AuthenticationFailureHandlerInterface.php';
include_once $this->targetDirs[3].'/src/Security/ApiKeyAuthenticator.php';

return $this->privates['security.authentication.listener.simple_preauth.main'] = new \Symfony\Component\Security\Http\Firewall\SimplePreAuthenticationListener(($this->services['security.token_storage'] ?? $this->services['security.token_storage'] = new \Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorage()), ($this->privates['security.authentication.manager'] ?? $this->getSecurity_Authentication_ManagerService()), 'main', ($this->privates['App\Security\ApiKeyAuthenticator'] ?? $this->privates['App\Security\ApiKeyAuthenticator'] = new \App\Security\ApiKeyAuthenticator()), ($this->privates['monolog.logger.security'] ?? $this->load('getMonolog_Logger_SecurityService.php')), ($this->services['event_dispatcher'] ?? $this->getEventDispatcherService()));
