<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'snc_redis.command.flush_db' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/console/Command/Command.php';
include_once $this->targetDirs[3].'/vendor/symfony/dependency-injection/ContainerAwareInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/framework-bundle/Command/ContainerAwareCommand.php';
include_once $this->targetDirs[3].'/vendor/snc/redis-bundle/Command/RedisBaseCommand.php';
include_once $this->targetDirs[3].'/vendor/snc/redis-bundle/Command/RedisFlushdbCommand.php';

$this->privates['snc_redis.command.flush_db'] = $instance = new \Snc\RedisBundle\Command\RedisFlushdbCommand();

$instance->setName('redis:flushdb');

return $instance;
